openapi: 3.0.3

info:
  title: PaySecure Payout API
  version: 1.0.0

servers:
  - url: https://api.paysecure.net

paths:
  /api/v1/getpayout/{payoutId}:
    get:
      tags:
        - PAYOUT
      summary: Get payout details by payoutId

      parameters:
        - in: path
          name: payoutId
          required: true
          schema:
            type: string

      responses:
        '202':
          description: Payout details response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PayoutPaid'
                  - $ref: '#/components/schemas/PayoutInProcess'
                  - $ref: '#/components/schemas/PayoutError'

        '404':
          description: Payout not found

components:
  schemas:

    BasePayout:
      type: object
      properties:
        payoutId:
          type: string
        amount:
          type: number
        currency:
          type: string
        status:
          type: string
        merchantRef:
          type: string
        merchantName:
          type: string
        created_on:
          type: integer
        updated_on:
          type: integer

    PayoutPaid:
      allOf:
        - $ref: '#/components/schemas/BasePayout'
        - type: object
          properties:
            status:
              type: string
              example: PAID
            paymentOn:
              type: integer
              example: 1755778408

    PayoutInProcess:
      allOf:
        - $ref: '#/components/schemas/BasePayout'
        - type: object
          properties:
            status:
              type: string
              example: PAYOUT_IN_PROCESS
            checkout_url:
              type: string
              example: https://api.choicepay.ca/payout/689f2f46cacb7166336f8c90/

    PayoutError:
      allOf:
        - $ref: '#/components/schemas/BasePayout'
        - type: object
          properties:
            status:
              type: string
              example: ERROR
            errorMsg:
              type: string
              example: Insufficient Balance [-1439.25]
